In [60]:
import numpy as np

In [225]:
#1
A=[[1,4,2,3,4,5],[2,5,6,5,2,1]]
B=[1,2,3,4,5,6]
C=[3.5,2.4]
D=[[2.2,2.2,2.2,2.2,2.2,2.2],[2.2,2.2,2.2,2.2,2.2,2.2]]

In [64]:
A=np.array(A)
B=np.array(B)
C=np.array(C)
D=np.array(D)

In [68]:
C.reshape(2,1)*(3*A-D)*B

array([[  2.8 ,  68.6 ,  39.9 ,  95.2 , 171.5 , 268.8 ],
       [  9.12,  61.44, 113.76, 122.88,  45.6 ,  11.52]])

In [223]:
#2
A=np.array([[11,12,13,14,15,16],
   [17,18,19,20,21,22],
   [23,24,25,26,27,28],
   [29,30,31,32,33,34]])


In [121]:
A

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [135]:
A[0:2,3:6]

array([[14, 15, 16],
       [20, 21, 22]])

In [137]:
A[::2]

array([[11, 12, 13, 14, 15, 16],
       [23, 24, 25, 26, 27, 28]])

In [151]:
A[0:4,4]

array([15, 21, 27, 33])

In [201]:
a=[A[:,1]]

In [203]:
b=[A[:,4]]

In [205]:
np.concatenate((a,b))

array([[12, 18, 24, 30],
       [15, 21, 27, 33]])

In [219]:
A[::2,1::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [235]:
#3
A=np.array([[2,4],[0,1]])
B=np.array([[1,1],[1,1]])

In [237]:
B/A

/var/folders/0m/0jnck1zx6kq11cw1v2n0xcqc0000gn/T/ipykernel_9106/2512182345.py:1: RuntimeWarning: divide by zero encountered in divide
  B/A


array([[0.5 , 0.25],
       [ inf, 1.  ]])

In [286]:
a=B/A

/var/folders/0m/0jnck1zx6kq11cw1v2n0xcqc0000gn/T/ipykernel_9106/3858841383.py:1: RuntimeWarning: divide by zero encountered in divide
  a=B/A


In [288]:
a[np.isinf(a)]=-1

In [290]:
a

array([[ 0.5 ,  0.25],
       [-1.  ,  1.  ]])